#11_NumPy_★_Indexing_and_Slicing

In [ ]:
import numpy as np
# A is a 2-d array
def get_column_from_bottom_to_top( A, c ):
  return A[::-1,c]

def get_odd_rows( A ):
  return A[1::2]

def get_even_column_last_row( A ):
  return A[-1,0::2]

def get_diagonal1( A ):# A is a square matrix
# from top-left corner down to bottom-right corner
  outout = []
  for i in range(A.shape[0]):
    outout.append(A[i,i])
  return np.array(outout)
def get_diagonal2( A ): # A is a square matrix
# from top-right corner down to bottom-left corner
  outout = []
  for i in range(0,-A.shape[0],-1):
    outout.append(A[-i,i-1])
  return np.array(outout)

exec(input().strip())

A=np.array([[1,2,3],[4,5,6],[7,8,9]]); print(get_diagonal2(A))
[3 5 7]


#11_NumPy_★_Scalar_and_Array

In [ ]:
import numpy as np
def toCelsius(f):
  return (f-32)*5/9

def BMI(wh):
  w = wh[:,0]
  h = wh[:,1]
  h = h/100
  h = h**2
  B = w/h
  return B
  pass

def distanceTo(p,Points):
  dxdy = Points-p
  dx = dxdy[:,0]
  dy = dxdy[:,1]
  d = (dx**2+dy**2)**0.5
  return d

exec(input().strip())

print(distanceTo([0,0],np.array([[3,0],[0,4],[3,4]])))
[[3 0]
 [0 4]
 [3 4]]
[3 0 3]
[0 4 4]
[ 4.5  8.  12.5]
[9 0 9]
[ 0 16 16]
[ 9 16 25]
None


#11_​NumPy_​★_​Logistic_​Regression

In [ ]:
import numpy as np
import math
def p(x):
  ps = x[:,0]
  gpa = x[:,1]
  logit = -3.98 + 0.1*ps + 0.5*gpa
  return 1/(1+math.e**(-logit))

exec(input().strip())

print(p(np.array([[100,4.00]])))
[8.02]
[100.]
[4.]
[0.99967129]


#11_NumPy_★★_Slicing and Element-wise Op.

In [ ]:
import numpy as np
def sum_2_rows(M):
  out = []
  for i in range(0,M.shape[0],2):
      out.append(M[i:i+2].sum(axis=0))
  return np.array(out)

def sum_left_right(M):
  out = []
  mid = int(M.shape[1]/2)
  for i in range(M.shape[0]):
    outout = []
    for j in range(mid):
        outout.append(M[i,j]+M[i,j+mid])
    outout = np.array(outout)
    out.append(outout)

  return np.array(out)

def sum_upper_lower(M):
  out = []
  mid = int(M.shape[0]/2)
  for i in range(mid):
    out.append(M[i,:]+M[i+mid,:])
  return np.array(out)

def sum_4_quadrants(M):
  lr = sum_left_right(M)
  ul = sum_upper_lower(sum_left_right(M))
  return ul

def sum_4_cells(M):
  out = []
  for i in range(0,M.shape[0],2):
    rr = M[i,:]+M[i+1,:]
    outout = []
    for j in range(0,M.shape[1],2):
      outout.append((rr[j]+rr[j+1]))
    out.append(outout)
  return np.array(out)

def count_leap_years(M):
  c = 0
  for i in range(M.shape[0]):
    y = M[i] - 543
    if y%4==0 and y%100!=0:
      c += 1
    elif y%400== 0:
      c +=1
  return c


exec(input().strip())

print(count_leap_years(np.array([2143, 2543, 2544, 2643, 2562, 2559, 2560, 2561, 2547, 2562, 2563])))
(11,)
5


#11_NumPy_★★_Outer_Product

In [ ]:
import numpy as np

def mult_table(nrows,ncols):
  a = []
  for i in range(nrows):
    a.append((i+1)*np.arange(1,ncols+1))
  return np.array(a)

exec(input().strip())

print(mult_table(3,4))
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


#11_NumPy_★★_Lower_than_Mean

In [ ]:
import numpy as np

def read_data():
  w = [float(e) for e in input().split()]
  weight = np.array(w)
  n = int(input())
  data = np.ndarray((n,4),int)
  for i in range(n):
    data[i] = [int(e) for e in input().split()]
  return weight, data

def report_lower_than_mean(weight, data):
    result = []
    out = []
    for i in range(data.shape[0]):
        outout = []
        for j in range(data.shape[1]):
          if j > 0:
              outout.append(weight[j-1]*data[i,j])
        outout.append(sum(outout))
        outout.insert(0,data[i,0])
        result.append(outout)
    np.set_printoptions(precision=2, suppress=True)
    result = np.array(result)
    avg = float(result.sum(0)[4]/result.shape[0])
    for i in range(result.shape[0]):
       if result[i,4] < avg:
          out.append(result[i,0])
    if len(out) != 0:
        for i in range(len(out)):
           out[i] = str(int(out[i]))
        print(', '.join(out))
    else:
       print('None')


exec(input().strip())

#11_NumPy_★★_Peak_Indexes

In [ ]:
import numpy as np
def peak_indexes(x):
  out = []
  for i in range(x.shape[0]):
    if i < x.shape[0]-1 and i != 0:
      if x[i] > x[i-1] and x[i] > x[i+1]:
        out.append(i)

  return out
def main():
  d = np.array([float(e) for e in input().split()])
  pos = peak_indexes(np.array(d))
  if len(pos) > 0:
    print(", ".join([str(e) for e in pos]))
  else:
    print("No peaks")
exec(input().strip()) # Don't remove this line

main()
1 9 1 9 1 9 1 9 1 9 1
1, 3, 5, 7, 9


#NumPy_P4_★★_Book Sales

In [ ]:
x = [float(e) for e in input().split()]
niyai = [float(e) for e in input().split()]
sarakadi = [float(e) for e in input().split()]
tongtiew = [float(e) for e in input().split()]
cartoon = [float(e) for e in input().split()]
mon_sum = 0
tue_sum = 0
wed_sum = 0
thu_sum = 0
fri_sum = 0
mon_book = 0
tue_book = 0
wed_book = 0
thu_book = 0
fri_book = 0
mon_sum += x[0]*niyai[0]+x[1]*sarakadi[0] + x[2]*tongtiew[0]+x[3]*cartoon[0]
tue_sum += x[0]*niyai[1]+x[1]*sarakadi[1] + x[2]*tongtiew[1]+x[3]*cartoon[1]
wed_sum += x[0]*niyai[2]+x[1]*sarakadi[2] + x[2]*tongtiew[2]+x[3]*cartoon[2]
thu_sum += x[0]*niyai[3]+x[1]*sarakadi[3] + x[2]*tongtiew[3]+x[3]*cartoon[3]
fri_sum += x[0]*niyai[4]+x[1]*sarakadi[4] + x[2]*tongtiew[4]+x[3]*cartoon[4]
mon_book += niyai[0]+sarakadi[0] + tongtiew[0]+cartoon[0]
tue_book += niyai[1]+sarakadi[1] + tongtiew[1]+cartoon[1]
wed_book += niyai[2]+sarakadi[2] + tongtiew[2]+cartoon[2]
thu_book += niyai[3]+sarakadi[3] + tongtiew[3]+cartoon[3]
fri_book += niyai[4]+sarakadi[4] + tongtiew[4]+cartoon[4]
out = [mon_sum, tue_sum, wed_sum, thu_sum, fri_sum]
book = [mon_book, tue_book, wed_book, thu_book, fri_book]
max_ = max(book)
if book.index(max_) == 0:
  print('Mon', max_)
elif book.index(max_) == 1:
  print('Tue', max_)
elif book.index(max_) == 2:
  print('Wed', max_)
elif book.index(max_) == 3:
  print('Thu', max_)
elif book.index(max_) == 4:
  print('Fri', max_)
out = [str(e) for e in out]
print(' '.join(out))

10 20 30 40
0 0 1 0 0
2 0 2 0 2
3 1 0 0 0
2 1 2 0 1
Mon 7.0
210.0, 70.0, 130.0, 0.0, 80.0


#

In [ ]:
import numpy as np
def read_height_weight():
  list_hw = []
  for k in range(int(input())) :
    h,w = input().split()
    list_hw.append((int(h),int(w)))
  return np.array(list_hw)
def cm_to_m(x):
  a = x.copy()
  a = a/100
  return a
def cal_bmi(hw):
  m_ = cm_to_m(hw[:,0])
  m_ = m_**2
  h_ = hw[:,1]/m_
  return h_
def main():
  hw = read_height_weight()
  bmi = cal_bmi(hw)
  avg_bmi = np.sum(bmi)/len(bmi)
  count_underweight = np.sum(bmi<18.5)
  print('average bmi =', avg_bmi)
  print('#bmi < 18.5 =', count_underweight)
exec(input().strip())

main()
4
180 55
170 54
155 62
160 60
average bmi = 21.22609534053624
#bmi < 18.5 = 1
